/* Generated by automated build script */
#define RELEASE 0.79
#define TEXTVER "Release 0.79 - Gary Sandi Vigabriel - gary.gsv@gmail.com"
#define SSHVER "-Release-0.79"
#define BINARY_VERSION 0,79,0,0
