/* Generated by automated build script */
#define RELEASE 0.83
#define TEXTVER "Release 0.83 - Gary Sandi Vigabriel - gary.gsv@gmail.com"
#define SSHVER "-Release-0.83"
#define BINARY_VERSION 0,83,0,0
